version: "3"
services:
  redis:
    container_name: redis6
    image: redis:6-alpine
    ports:
      - ${REDIS_PORT}:6379
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    ports:
      - ${REDIS_COMMANDER_PORT}:8081
    env_file:
      - .env
